name: flutter_avision
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  retrofit: ^4.0.1
  json_annotation: ^4.8.0
  dio: ^5.1.1
  sn_progress_dialog: ^1.1.3
  hexcolor: ^3.0.1
  shared_preferences: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  image_picker: ^0.8.3
  double_back_to_close_app: ^2.1.0
  http: ^0.13.5
  flutter_launcher_icons: "^0.13.1"
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  youtube_player_flutter: ^8.1.2
  flutter:
    sdk: flutter


flutter_launcher_icons:
  image_path: "assets/image/logo1.png"
  android: true
  ios: true
  min_sdk_android: 21

 

dev_dependencies:
  retrofit_generator: ^6.0.0+1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/

    

  
